project:
  type: website
  output-dir: _site

website:
  title: "Smart-Profile"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

        
  #Footer-----------------------------------------------------------------------       
  page-footer:
    left: |
      | © SMATER.ME 2025
    center: "GET SMART PROFILES"
    right: "Built with [Quarto](https://quarto.org/)"
#Format-------------------------------------------------------------------------     
format:
  html: 
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 300px
      gutter-width: 1.5rem
    code-fold: true
    theme:
      light: flatly
      dark: darkly
    page-layout: full
    fig-dpi: 300
    toc: true
    embed-resources: true
    self-contained: true
css: styles.css



