project:
  type: website
  output-dir: _site

website:
  title: "SMATER.ME"
  site-url: "https://www.smater.me"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: profiles.qmd
        text: Profiles
      
      # - text: "Profiles"
      #   icon: atom
      #   menu:
      #     - text: "Marothi Peter LETSOALO"
      #       href: static/marothi-letsoalo/index.html
        
    right:
      - about.qmd
      - href: register.qmd
        text: Create Profile

        
  #Footer-----------------------------------------------------------------------       
  page-footer:
    left: |
      | © SMATER.ME 2025
    center: "GET SMART PROFILES"
    right: "Built with [Quarto](https://quarto.org/)"
#Format-------------------------------------------------------------------------     
format:
  html: 
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 300px
      gutter-width: 1.5rem
    code-fold: true
    theme:
      light: flatly
      dark: darkly
    page-layout: full
    fig-dpi: 300
    toc: true
    embed-resources: true
    self-contained: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
css: styles.css

# Add this section to ensure your files are copied
resources:
  - static/



